spring.application.name=HuynhNgocQuocThai_tuan01


#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.port=8080

spring:
security:
oauth2:
resourceserver:
jwt:
public-key-location: classpath:public.key

